name: congorna
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # firebase_core: ^0.4.4
  firebase_core: ^0.4.4
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  # cloud_firestore: ^0.14.0+2

  google_fonts: ^1.1.0
  device_preview: ^0.3.0+1
  font_awesome_flutter: ^8.8.1
  rxdart: ^0.24.1
  provider: ^4.1.3
  uuid: ^2.1.0
  intl: ^0.16.1
  dio: ^3.0.10
  ndialog: ^3.1.0
  fluttertoast: ^4.0.1
  firebase_storage: ^3.1.3
  image_picker: ^0.6.7+3
  permission_handler: ^5.0.1+1
  flutter_native_image: ^0.0.5+2
#  flutter_svg: ^0.17.4
  flutter_svg: ^0.18.0
  flutter_secure_storage: ^3.2.1+1
  country_code_picker: ^1.1.7
  pin_view: ^1.0.1
  firebase_dynamic_links: ^0.5.0+1
  flutter_login_facebook: ^0.2.1
  # flutter_facebook_login: ^3.0.0
  flutter_signin_button: ^1.0.0
  webview_flutter: ^0.3.22+1
  cached_network_image: ^2.2.0+1
  google_maps_flutter: ^0.5.30
  flutter_polyline_points: ^0.2.2
  location: ^3.0.2
  google_maps_webservice: ^0.0.18
  geolocator: ^5.3.2+2
  flutter_google_places: ^0.2.6
  flutter_spinkit: "^4.1.2"
  firebase_messaging: ^6.0.16


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  uses-material-design: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/
    - assets/car_icon.png
    - assets/marker.png
    - assets/images/add.png
    - assets/images/map.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: BigJohnPRO
      fonts:
      - asset: assets\fonts/BigJohnPRO-Light.otf
      - asset: assets\fonts/BigJohnPRO-Regular.otf
        weight: 600
      - asset: assets\fonts/BigJohnPRO-Bold.otf
        weight: 700
        style: italic
    - family: Machine
      fonts:
      - asset: assets\fonts/NeueMachina-Light.otf
      - asset: assets\fonts/NeueMachina-Regular.otf
        weight: 600
      - asset: assets\fonts/NeueMachina-Ultrabold.otf
        weight: 700
        style: italic
    - family: Hagrid
      fonts:
      - asset: assets\fonts/Hagrid-Italic-trial.ttf
      - asset: assets\fonts/Hagrid-Regular-trial.ttf
        weight: 600
      - asset: assets\fonts/Hagrid-Text-Extrabold-Italic-trial.ttf
      - asset: assets\fonts/Hagrid-Text-Extrabold-trial.ttf
        weight: 700
        style: italic
    - family: BubbleGum
      fonts:
      - asset: assets\fonts/BubbbleGum-Light.otf
      - asset: assets\fonts/BubbbleGum.otf
        weight: 600
      - asset: assets\fonts/BubbbleGum-Black.otf
        weight: 700
        style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
